# REGEX : [Replacement Name, Cat, SubCat]
# Match Name and convert for database



payees = {
# Bills
"nm gas" : ["NM Gas Company", "Bills", "Gas"],
"NewMexicoGasCompany" : ["NM Gas Company", "Bills", "Gas"],
"PNM" : ["NM Gas Company", "Bills", "Electricity"],
"STATE FARM" : ["State Farm", "Bills", "Auto Insurance"],
"NAME-CHEAP.COM" : ["Namecheap", "Bills", "Hosting/Website"],
"Chase" : ["Chase Bank", "Bills", "Credit Card"],
"wells fargo" : ["Wells Fargo", "Bills", "Credit Card"],
"WF Credit Card" : ["Wells Fargo", "Bills", "Credit Card"],
"VZ Wireless" : ["Verizon Wireless", "Bills", "Cell Phone"],
"dept of edu" : ["Deptartment Of Education", "Bills:Student Loan Payment", ""],
"FEDLOANSERVICING" : ["Deptartment Of Education", "Bills:Student Loan Payment", ""],
"Instacart|Dashing|Uber LLC|Postmates|Doordash" : ["Delivery", "Dining Out:Delivery", ""],
"Envato" : ["Envato Marketplace", "Website", ""],
"COMCAST" : ["Comcast Xfinity", "Bills:Internet", ""],
"VZ Wireless" : ["Verizon Wireless", "Bills", ""],
"plex" : ["Plex", "Services/Memberships:Video Streaming", ""],
"BEST BUY" : ["Best Buy", "Hobbies/Leisure:Electronics", ""],
"ONKYO SERVICE" : ["ONKYO SERVICE", "Hobbies/Leisure:Electronics", ""],
"CANAKIT.COM" : ["Canakit.com", "Hobbies/Leisure:Electronics", ""],
"BESTBUY" : ["Best Buy", "Hobbies/Leisure:Electronics", ""],
"NEWEGG" : ["Newegg", "Hobbies/Leisure:Electronics", ""],
"Nevins Adams Lew" : ["Rancho Carrera", "Rancho Carrera", ""],
"SPLICE.COM" : ["Splice", "Hobbies/Leisure:Music Prdouction", ""],
"AGAPAO COFFEE" : ["Agapao Coffee", "Groceries:Coffee", ""],
"ADAGIO TEAS " : ["Adagio", "Groceries:Tea", ""],
    "coffee" : ["Coffee Shop", "Dining Out:Coffee", ""],
    "STARBUCKS" : ["Starbucks", "Dining Out:Coffee", ""],
"Bill payment Withdrawal GOOGLE" : ["Google Vendor", "Services/Memberships", ""],
"getmailbird" : ["Mail Bird", "Work Expense", ""],
"emclient" : ["EMClient", "Work Expense", ""],

# hobbies and liesure
"total wine" : ["Total Wine and More", "Hobbies/Leisure:Alcohol/Beer/Wine", ""],
"!*norename*!|eBay|ebaycommerce" : ["eBay", "Hobbies/Leisure:Online Shopping", ""],
"hobbylobby" : ["hobbylobby", "Hobbies/Leisure", ""],

# Dining Out
"Burrito Company|Carls Jr|Chicago Dog|Blake's LOTABURGER|WHOO'S DONUTS|5GUYS|Mcalister's|Refresqueria Las Delicia|Papa Murphy's|CELINA'S BISCOCHITOS|Shake Foundation|McDonald's|Real Burger|Dunkin Doughnuts|Dairy Queen|Tikka Spice Food|Dions|Chick-Fil-A|Taco Bell|Jimmy Johns|Fast And Real|fast & Real|El Parasol|Chicken|Sonic|Burger King|Chipotle" : ["Restaraunt", "Dining Out:Fast Food", ""],
"Masa Sushi|Cafe Atalaya|IL VICINO|CLEOPATRA CAFE|Realburger|Jinja|Kohnami|Lion & Honey|Loyal Hound|Mampuku Ramen|Michael's Kitchen|Mucho Gourmet Sandwich|New York Deli|Pappadeaux|Piccolino Italian|Posas On Zafarano|Jambo Cafe|The Compound Restaurant|The Ranch House|Vinaigrette|Violet Crown Cinema|Del Charro|Clafoutis|Applebees|Chiles|Wecks|Capitol Grill|Plaza|Second Street|Adelitas|Boxcar|SANTA FE TEA HOUSE|" : ["Restaraunt", "Dining Out:Restaraunt", ""],
"Santa Fe Brewing|WINE|Rufina|Fire & Hops|Bar|Tap Room|Tumbleroot|Tonic|Black Mesa Winery" : ["Bar", "Dining Out:Bar", ""],
"!*norename*!|Rowleys|Rowley Farmhouse Ales" : ["Rowley Farmhouse Ales", "Dining Out:Bar", ""],
"BILL DEUTSCH" : ["Santa Fe Coffee Shop", "Dining Out:Coffee", ""],
"HORSEMAN S HAVEN" : ["Horesman's Haven", "Dining Out:Restaraunt", ""],

# Groceries
"SPROUTS FARMERS MKT" : ["Sprouts Farmer's Market", "Groceries", ""],
"NESPRESSO" : ["Nespresso", "Groceries:Coffee", ""],
"CSV|Target|Walmart|Wholefoods|Smiths|Walgreens|Family Dollar|Dollar General|H-E-B|BIG LOTS" : ["Groceries", "Groceries", ""],
"WHOLEFDS" : ["Wholefoods", "Groceries", ""],
"CHEWY.COM" : ["CHEWY.COM", "Pet Care", ""],
"PETSMART" : ["Petsmart", "Pet Care", ""],
"GRUDA VETERINARY HOSPITAL" : ["Gruda Vet", "Pet Care:Vet", ""],

# shopping
"ITUNES" : ["Apple", "Hobbies/Leisure:Music/Cds", ""],
"APPLE.COM" : ["Apple", "Hobbies/Leisure:Digital Goods", ""],
"Card purchase GOOGLE" : ["Google Vendor", "Hobbies/Leisure:Digital Goods", ""],
"GOOGLE" : ["Google", "Hobbies/Leisure:Digital Goods", ""],
"EA" : ["ELECTRONIC ARTS", "Hobbies/Leisure:Video Games", ""],
"!*norename*!|steam|steamgames" : ["Valve", "Hobbies/Leisure:Video Games", ""],
"!*norename*!|blizzard|blizzard Entertainment" : ["Blizzard Entertainment", "Hobbies/Leisure:Video Games", ""],
"HUMBLEBUNDLE" : ["Humble Bundle", "Hobbies/Leisure:Video Games", ""],
"AMAZON.COM" : ["Amazon", "Hobbies/Leisure:Online Shopping", ""],
"kindle Svcs" : ["Amazon", "Hobbies/Leisure:Books", ""],
"AMZN" : ["Amazon", "Hobbies/Leisure:Online Shopping", ""],
"Card purchase AMZN" : ["Amazon", "Hobbies/Leisure:Online Shopping", ""],
"Harman/JBL/AKG/INF|adorama.com" : ["Harman/JBL/AKG/INF", "Hobbies/Leisure:Audio", ""],
"MERCARI" : ["Mercari", "Hobbies/Leisure:Audio", ""],
"refund" : ["Refund", "Refunds", ""],
"return" : ["Refund", "Refunds", ""],
"!*norename*!|TOPAZ LABS SOFTWAR|topaz Labs Software|topaz" : ["Topaz Labs", "Work Expenses:Graphic Design", ""],
"Wayfair" : ["Wayfair", "Work Expenses", ""],
"Cephalofair|Big Adventure Comics|Ninthhaven.com|401 Games|GAMEARENA|Gamefound|CAPSTONE GAMES|WOLFF DESIGNA|Miniature Market|COOLSTUFFINC|SERIOUSPOULP|KICKSTARTER|Gamenerdz|The LUMENARIS GROUP|Pozdnak Artem|Luckyduckgames|Boardgamebliss" : ["Board Games", "Hobbies/Leisure:Board Games", ""],
"DSW|Adidas|Nordstrom|Ralph Lauren|KATESPADE|freepeople.com" : ["Clothing Store", "Gifts:Courtney", ""],
"Lette Macarons" : ["Lette Macarons", "Gifts:Courtney", ""],
"www.sugarbearhair.com" : ["Sugarbearhair", "Gifts:Courtney", ""],
"MACYS|Dillards|JCpenney|TJ Max|Kohls|Ross Stores" : ["Clothing Store", "Clothing", ""],


# Personal Care
"covenant eyes" : ["Covenant Eyes", "Personal Care", ""],
"total wine" : ["Total Wine and More", "Hobbies/Leisure:Alcohol/Beer/Wine", ""],
"primo's Cigar Shop" : ["Primo's Cigar Shop", "Hobbies/Leisure:Alcohol/Beer/Wine", ""],
"SUSANS FINE WINE" : ["Susan's", "Hobbies/Leisure:Alcohol/Beer/Wine", ""],
"Stanton Optical" : ["Stanton Optical", "Personal Care:Eyeware", ""],
"fillmore Eye Clinic" : ["Fillmore Eye Clinic", "Personal Care:Eyeware", ""],
"*EVOLUTION HAIR" : ["Evolution Hair Care", "Personal Care:Hair Cut", ""],
"!*norename*!|Liquor|Liquors|Beer|Wine|Spirits" : ["Liquor Store", "Hobbies/Leisure:Alcohol/Beer/Wine", ""],

# Other
"!*norename*!|FAMECARE.COM|FAMEHELP.COM|fxhelpsupport.com|IPROSUPPORT.COM|PWIHELP.COM|OLIFEHELP.COM|SEEMYHELP.COM|VIDBILLING.COM|VXNBILL.COM|cshelpcenter.com|ADLTIME1.COM|BILLHELP247.COM|ADLTIME1.COM|HLPTECH|SEGPAY|SALES-CS.COM|PROBILLER|epoch|NVG MOBILE|CCBill.com|GIRLSGONEWILD.COM" : ["Vice", "Services/Memberships", ""],
"Lowe's Home" : ["Lowe's Home Improvement", "Home Improvement", ""],
"MICHAELS STORES" : ["Michael's", "Home Improvement:Crafts", ""],
"go big" : ["Go Big Inc", "Wage & Salary", ""],
"NEW MEXICO SCHOO" : ["NMSA", "Wage & Salary", ""],
"Check Deposit Mobile deposit" : ["Check Deposit Mobile Deposit", "Deposit:Check", ""],
"dividend deposit" : ["DNCU", "Investment Income:Dividends", ""],
"chicken|pizza|tacos" : ["Restaraunt", "Dining Out:Restaraunt", ""],
"Allsups|Shell|Chevron|LATINOS UNIDOS|Speedway|Phillips 66" : ["Gas", "Other", ""],
"IRS" : ["IRS", "Taxes", ""],
"Code With Mosh|Udemy" : ["CODE WITH MOSH", "Education", ""],
"PARKING" : ["Parking Fee", "Fees:Parking", ""],
"ELDORADO HOTEL" : ["Eldorado Hotel", "Dining Out:Delivery", ""],
"!*norename*!|NessysTreasure|Nessystreasur" : ["Etsy", "Wedding", ""],
"usps" : ["USPS", "Other", ""],
"fedex" : ["Fedex", "Other", ""],
"Bernie" : ["Bernie Sanders", "Political Donation", ""],
"ACTBLUE" : ["ACTBLUE", "Political Donation", ""],
"TULSI NOW" : ["TULSI NOW", "Political Donation", ""],
"NEW MEXICO RIVER" : ["New Mexico River Tours", "Hobbies/Leisure", ""],
"newman's Nursery" : ["Newman's Nursery", "Hobbies/Leisure:Gardening", ""],
"MOONLITWEDDINGS.COM" : ["Moonlit Weddings", "Wedding", ""],
"AUTOZONE|Oreilly|Jiffylube" : ["USPS", "Other", ""],
"Robinhood|Fidelity" : ["Stocks", "Assets:Stocks", ""],
"ADOBE" : ["Adobe", "Work Expense:Graphic Design", ""],
"Creative Cloud" : ["Adobe", "Work Expense:Graphic Design", ""],
"usps" : ["USPS", "Other", ""],
"BEDBATH&BEYOND" : ["Bed Bath & Beyond", "Shopping", ""],
"Savers|Office Depot" : ["Savers|", "Shopping", ""],
"MCCALLS PUMPKIN PATCH" : ["MCCALLS PUMPKIN PATCH", "Hobbies/Leisure", ""],
"Lyft|Uber" : ["Rideshare", "Transportation", ""],
"Motor Vehicles" : ["MVD", "Automobile:Registration", ""],
"ten Thousand Waves" : ["Ten Thousand Waves", "Hobbies/Leisure", ""],
"tularosa Travel Center" : ["Tularosa Travel Center", "Hobbies/Leisure", ""],
"h&r Block" : ["H&R Block", "Taxes:Preperation", ""],
"wix.com" : ["Wix", "Work Expense:Client", ""],
"aescripts.com" : ["Aescripts.com", "Work Expense", ""],
"sarahs Candies" : ["Candy Store", "Shopping", ""],
"chicagonewsst1725" : ["Chicago One West", "Shopping", ""],
}